---
abstract: "Override LWP's HTTP/HTTPS backend with your own PSGI applciation"
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  Module::Build::Tiny: 0.023
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWP-Protocol-PSGI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Guard: 0
  HTTP::Message::PSGI: 0
  LWP: 5
  LWP::Protocol: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/miyagawa/LWP-Protocol-PSGI/issues
  homepage: https://github.com/miyagawa/LWP-Protocol-PSGI
  repository: https://github.com/miyagawa/LWP-Protocol-PSGI.git
version: 0.05
x_contributors:
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
